name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - name: Pull all dependencies and build UI
        run: make build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
